//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Notifications {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notifications() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Notifications", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have added {0} to your items collection..
        /// </summary>
        internal static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An offer has been made for your {0} in exchange for {1}.
        /// </summary>
        internal static string AddTradeReceiver {
            get {
                return ResourceManager.GetString("AddTradeReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have offered your {0} in exchange for {1}.
        /// </summary>
        internal static string AddTradeSender {
            get {
                return ResourceManager.GetString("AddTradeSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have added {0} to your wishlist..
        /// </summary>
        internal static string AddWishItem {
            get {
                return ResourceManager.GetString("AddWishItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The offer of {0} in exchange for {1} has been approved!.
        /// </summary>
        internal static string ConfirmTrade {
            get {
                return ResourceManager.GetString("ConfirmTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have deleted {0} from your items collection..
        /// </summary>
        internal static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have made changes to {0} in your items collection..
        /// </summary>
        internal static string EditItem {
            get {
                return ResourceManager.GetString("EditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmed offer page of {0} for {1} has expired. The associated items have been removed from your collection..
        /// </summary>
        internal static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmed offer page of {0} for {1} is going to expire soon. Have you recorded contact information?.
        /// </summary>
        internal static string ExpireWarning {
            get {
                return ResourceManager.GetString("ExpireWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The offer of {0} for {1} has been canceled..
        /// </summary>
        internal static string RemoveTrade {
            get {
                return ResourceManager.GetString("RemoveTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have removed {0} from your wishlist..
        /// </summary>
        internal static string RemoveWishItem {
            get {
                return ResourceManager.GetString("RemoveWishItem", resourceCulture);
            }
        }
    }
}
