//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Processing {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Processing() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Processing", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been cancelled, create a new account to login..
        /// </summary>
        internal static string ProcessAccountRemoved {
            get {
                return ResourceManager.GetString("ProcessAccountRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find information for this item..
        /// </summary>
        internal static string ProcessEditNoForm {
            get {
                return ResourceManager.GetString("ProcessEditNoForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is already registered to an account..
        /// </summary>
        internal static string ProcessEmailExists {
            get {
                return ResourceManager.GetString("ProcessEmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address was not entered correctly..
        /// </summary>
        internal static string ProcessEmailNotFound {
            get {
                return ResourceManager.GetString("ProcessEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process your request, please try again..
        /// </summary>
        internal static string ProcessError {
            get {
                return ResourceManager.GetString("ProcessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered credentials are incorrect..
        /// </summary>
        internal static string ProcessIncorrectLogin {
            get {
                return ResourceManager.GetString("ProcessIncorrectLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently have the maximum number of allowed uploads in your item collection.&lt;br&gt;You will not be able to add any more items until another is either confirmed for a trade or removed..
        /// </summary>
        internal static string ProcessMaxItems {
            get {
                return ResourceManager.GetString("ProcessMaxItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password entered is incorrect..
        /// </summary>
        internal static string ProcessPasswordIncorrect {
            get {
                return ResourceManager.GetString("ProcessPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password must be correctly entered twice..
        /// </summary>
        internal static string ProcessPasswordNoMatch {
            get {
                return ResourceManager.GetString("ProcessPasswordNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has already made a report on this user which is still pending..
        /// </summary>
        internal static string ProcessReportExists {
            get {
                return ResourceManager.GetString("ProcessReportExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success! Report has been sent..
        /// </summary>
        internal static string ProcessReportSent {
            get {
                return ResourceManager.GetString("ProcessReportSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success! Your {0} settings have been changed..
        /// </summary>
        internal static string ProcessSettingsConfirmed {
            get {
                return ResourceManager.GetString("ProcessSettingsConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is already taken..
        /// </summary>
        internal static string ProcessUsernameExists {
            get {
                return ResourceManager.GetString("ProcessUsernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is either incorrect or not found..
        /// </summary>
        internal static string ProcessUsernameNotFound {
            get {
                return ResourceManager.GetString("ProcessUsernameNotFound", resourceCulture);
            }
        }
    }
}
